import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

/** repo-root fixtures/ directory */
export const FIXTURES_DIR = join(here, '..', '..', '..', 'fixtures');

export function loadFixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(join(FIXTURES_DIR, name)));
}

export interface Golden {
  file: string;
  nst: number;
  ncolors: number;
  ext: [number, number, number, number]; // posX, posY, negX, negY
  offsets: { attribute: number; x: number; y: number; eof: number };
  commands: number[];
  xs: number[];
  ys: number[];
}

export function loadGolden(stem: string): Golden {
  const raw = readFileSync(join(here, 'golden', `${stem}.json`), 'utf-8');
  return JSON.parse(raw) as Golden;
}

export const FIXTURE_STEMS = ['001s-A', '028-B', '052-Z'] as const;

// ---------------------------------------------------------------------------
// Milestone-2 format goldens (generated by scripts/gen_format_golden.py)
// ---------------------------------------------------------------------------

import type { Command, Pattern, Stitch, Thread } from '../src/ir';
import { computeExtents } from '../src/ir';

export const GOLDEN_PATTERNS = [
  '001s-A',
  '028-B',
  '052-Z',
  'multicolor',
  'longjump',
  'trims',
] as const;

export const GOLDEN_FORMATS = ['dst', 'exp', 'jef', 'pes', 'pec', 'vp3', 'xxx'] as const;

export interface DumpedPattern {
  stitches: Array<[number, number, Command]>;
  threads: Array<{ rgb: number; description: string | null; catalog: string | null }>;
}

const formatsDir = join(here, 'golden', 'formats');

export function loadGoldenBytes(name: string, ext: string): Uint8Array {
  return new Uint8Array(readFileSync(join(formatsDir, `${name}.${ext}`)));
}

export function loadGoldenJson(
  name: string,
  kind: 'ir' | `${string}.normalized` | `${string}.read`,
): DumpedPattern {
  return JSON.parse(
    readFileSync(join(formatsDir, `${name}.${kind}.json`), 'utf-8'),
  ) as DumpedPattern;
}

/** Rebuild an IR Pattern from a dumped-pattern JSON. */
export function patternFromDump(dump: DumpedPattern): Pattern {
  const stitches: Stitch[] = dump.stitches.map(([x, y, command]) => ({ x, y, command }));
  const threads: Thread[] = dump.threads.map((t) => {
    const thread: Thread = { rgb: t.rgb };
    if (t.description !== null && t.description !== '') thread.description = t.description;
    if (t.catalog !== null && t.catalog !== '') thread.catalog = String(t.catalog);
    return thread;
  });
  return { stitches, threads, extents: computeExtents(stitches) };
}

/**
 * pyembroidery's trivial "stored" EmbCompress block (EmbCompress.compress):
 * a 6-byte header that sets up 8-bit literal passthrough Huffman tables,
 * followed by the raw data. expand() round-trips it (verified against
 * pyembroidery). Lets tests fabricate VIP files without a real compressor.
 */
export function storedBlock(data: number[]): number[] {
  const size = data.length;
  return [size & 0xff, (size >> 8) & 0xff, 0x02, 0xa0, 0x01, 0xfe, ...data];
}

import { VIP_COLOR_TABLE } from '../src/charts/vip-table';

const SYNTHETIC_VIP_COLORS = [0xff0000, 0x00ff00, 0x0000ff, 0xffff00, 0xff00ff];

/**
 * Build a minimal synthetic VIP file from raw records. `dy` is in VIP
 * orientation (the IR y will be its negation). An END record is appended.
 * The header uses the real fixture layout, including the XOR-encoded color
 * block at 0x2E and the (ncolors+1)×u32(1) + u16(0) trailer.
 */
export function buildSyntheticVip(
  records: Array<[cmd: number, dx: number, dy: number]>,
  ncolors: number,
  colors: number[] = SYNTHETIC_VIP_COLORS,
): Uint8Array {
  const commands = storedBlock([...records.map(([c]) => c), 0x90]);
  const xs = storedBlock([...records.map(([, dx]) => dx & 0xff), 0]);
  const ys = storedBlock([...records.map(([, , dy]) => dy & 0xff), 0]);

  const attributeOffset = 0x34 + 8 * ncolors;
  const xOffset = attributeOffset + commands.length;
  const yOffset = xOffset + xs.length;

  const bytes = new Uint8Array(yOffset + ys.length);
  const view = new DataView(bytes.buffer);
  view.setUint32(0x00, 0x0190fc5d, true); // VIP magic
  view.setInt32(0x04, records.length + 1, true); // nst incl. END
  view.setInt32(0x08, ncolors, true);
  view.setInt32(0x14, attributeOffset, true);
  view.setInt32(0x18, xOffset, true);
  view.setInt32(0x1c, yOffset, true);
  view.setInt32(0x2a, 0x2e + 8 * ncolors, true); // colorLength (fixture formula)
  // XOR-chained color block: 4 bytes per color (r, g, b, 0).
  let prev = 0;
  for (let i = 0; i < ncolors * 4; i++) {
    const rgb = colors[Math.floor(i / 4) % colors.length]!;
    const decoded = [(rgb >> 16) & 0xff, (rgb >> 8) & 0xff, rgb & 0xff, 0][i % 4]!;
    prev = (decoded ^ VIP_COLOR_TABLE[i]!) ^ prev;
    bytes[0x2e + i] = prev;
  }
  let p = 0x2e + 4 * ncolors;
  for (let i = 0; i <= ncolors; i++) {
    view.setUint32(p, 1, true);
    p += 4;
  }
  // u16(0) trailer then the compressed streams.
  bytes.set(commands, attributeOffset);
  bytes.set(xs, xOffset);
  bytes.set(ys, yOffset);
  return bytes;
}
