#!/usr/bin/env python3
"""Generate the JEF (85), PEC (64), HUS (29), SEW (79) and SHV (43) thread
chart TypeScript modules from pyembroidery's tables — never transcribe color
tables by hand.

Run from repo root:  python packages/core/scripts/gen_charts.py
"""
from pathlib import Path

from pyembroidery import EmbThreadHus, EmbThreadJef, EmbThreadPec, EmbThreadSew, EmbThreadShv

REPO = Path(__file__).resolve().parents[3]
CHARTS = REPO / "packages" / "core" / "src" / "charts"

HEADER = """\
// GENERATED by scripts/gen_charts.py from pyembroidery (MIT) — do not edit.
import type {{ Thread }} from '../ir';

/** `null` marks chart slots with no thread (index 0 of the JEF chart). */
export const {name}: ReadonlyArray<Thread | null> = [
"""


def emit(name, threads, out_path):
    lines = [HEADER.format(name=name)]
    for t in threads:
        if t is None:
            lines.append("  null,\n")
            continue
        rgb = t.color & 0xFFFFFF
        desc = (t.description or "").replace("'", "\\'")
        catalog = str(t.catalog_number or "").replace("'", "\\'")
        lines.append(
            f"  {{ rgb: 0x{rgb:06X}, description: '{desc}', catalog: '{catalog}' }},\n"
        )
    lines.append("];\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {out_path.relative_to(REPO)} ({len(threads)} entries)")


def emit_pec_blank(out_path):
    from pyembroidery.PecGraphics import get_blank
    b = get_blank()
    lines = [
        "// GENERATED by scripts/gen_charts.py from pyembroidery (MIT) — do not edit.\n",
        f"/** PEC 48x38 1-bit thumbnail frame template ({len(b)} bytes). */\n",
        "export const PEC_BLANK: readonly number[] = [\n",
    ]
    for i in range(0, len(b), 16):
        row = ", ".join(f"0x{v:02x}" for v in b[i:i + 16])
        lines.append(f"  {row},\n")
    lines.append("];\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {out_path.relative_to(REPO)} ({len(b)} bytes)")


def main():
    CHARTS.mkdir(parents=True, exist_ok=True)
    emit("JEF_THREADS", EmbThreadJef.get_thread_set(), CHARTS / "jef-threads.ts")
    emit("PEC_THREADS", EmbThreadPec.get_thread_set(), CHARTS / "pec-threads.ts")
    emit("HUS_THREADS", EmbThreadHus.get_thread_set(), CHARTS / "hus-threads.ts")
    emit("SEW_THREADS", EmbThreadSew.get_thread_set(), CHARTS / "sew-threads.ts")
    emit("SHV_THREADS", EmbThreadShv.get_thread_set(), CHARTS / "shv-threads.ts")
    emit_pec_blank(CHARTS / "pec-blank.ts")


if __name__ == "__main__":
    main()
