#!/usr/bin/env python3
"""Generate src/charts/vip-table.ts from the vendored libembroidery source.

The VIP color block XOR table (`vipDecodingTable`) must never be transcribed
by hand (see project memory: a manual copy-paste already caused a bug once).
This script parses the vendored C file and emits the TypeScript module,
verifying the known plaintext first: the fixture color bytes 1a 15 eb 84
must decode to RGB #348D1A.

Run from repo root:  python packages/core/scripts/gen_vip_table.py
"""
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC = REPO / "reference" / "vendor" / "libembroidery-unsorted.c"
OUT = REPO / "packages" / "core" / "src" / "charts" / "vip-table.ts"


def main() -> None:
    text = SRC.read_text(encoding="utf-8", errors="replace")
    m = re.search(
        r"vipDecodingTable\[\]\s*=\s*\{(.*?)\};", text, flags=re.DOTALL
    )
    if m is None:
        raise SystemExit("vipDecodingTable not found in vendored source")
    values = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(1))]
    if len(values) < 16:
        raise SystemExit(f"suspiciously short table ({len(values)} entries)")

    # Known-plaintext check against the fixtures (see docs/VIP_FORMAT.md):
    # encoded 1a 15 eb 84 --xor-chain--> 34 8d 1a 00 (#348D1A + 0 pad).
    encoded = [0x1A, 0x15, 0xEB, 0x84]
    prev = 0
    decoded = []
    for i, b in enumerate(encoded):
        decoded.append((b ^ values[i]) ^ prev)
        prev = b
    if decoded != [0x34, 0x8D, 0x1A, 0x00]:
        raise SystemExit(f"known-plaintext check FAILED: {[hex(d) for d in decoded]}")

    rows = []
    for i in range(0, len(values), 12):
        rows.append("  " + ", ".join(f"0x{v:02x}" for v in values[i : i + 12]) + ",")
    body = "\n".join(rows)
    OUT.write_text(
        "// GENERATED by scripts/gen_vip_table.py — do not edit by hand.\n"
        "// Source: reference/vendor/libembroidery-unsorted.c (libembroidery,\n"
        "// zlib/libpng license) — `vipDecodingTable`, the XOR keystream for the\n"
        "// VIP header color block. Verified against the fixture known plaintext\n"
        "// (encoded 1a 15 eb 84 -> #348D1A).\n"
        "\n"
        "export const VIP_COLOR_TABLE: readonly number[] = [\n"
        f"{body}\n"
        "];\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(REPO)} ({len(values)} entries), known-plaintext OK")


if __name__ == "__main__":
    main()
