#!/usr/bin/env python3
"""
REFERENCE IMPLEMENTATION (proven) — VIP reader + ZHS writer.

This is the *source of truth* to port to TypeScript. It was reverse-engineered
from real Artist Toolkit output and is verified:
  - 028-B.vip -> ZHS regenerated BYTE-IDENTICAL to fixtures/028-B.zhs
    (except 1 metadata byte at 0x83, see docs/ZHS_FORMAT.md)
  - All 52 letters: absolute stitch path of the generated ZHS matches the VIP source.

Dependencies: pyembroidery (only for EmbCompress.expand and signed8 helpers).
    pip install pyembroidery --break-system-packages

The EmbCompress "expand" routine is the classic Greg-Hus compression shared by
HUS / VIP / VP3. When porting to TS you must port expand() too (pyembroidery is
MIT-licensed, so porting is allowed). See docs/VIP_FORMAT.md.

Usage:
    python3 zhs_vip_reference.py convert  in.vip out.zhs
    python3 zhs_vip_reference.py verify    sample.vip sample.zhs   # round-trip check
"""
import struct, sys
from pyembroidery.EmbCompress import expand
from pyembroidery.ReadHelper import signed8

VIP_MAGIC = 0x0190FC5D

# ---------------------------------------------------------------------------
# VIP reader
# ---------------------------------------------------------------------------
def read_vip(path):
    """Return dict(nst, ext=(posX,posY,negX,negY), recs=[(cmd,dx,dy)...]).
    recs EXCLUDES the trailing END record. dy is VIP-oriented (ZHS y = -dy)."""
    d = open(path, "rb").read()
    if struct.unpack_from("<I", d, 0)[0] != VIP_MAGIC:
        raise ValueError("Not a VIP file: " + path)
    nst  = struct.unpack_from("<i", d, 4)[0]
    posX = struct.unpack_from("<h", d, 0x0C)[0]; posY = struct.unpack_from("<h", d, 0x0E)[0]
    negX = struct.unpack_from("<h", d, 0x10)[0]; negY = struct.unpack_from("<h", d, 0x12)[0]
    attr = struct.unpack_from("<i", d, 0x14)[0]
    xo   = struct.unpack_from("<i", d, 0x18)[0]
    yo   = struct.unpack_from("<i", d, 0x1C)[0]
    cmd = expand(bytearray(d[attr:xo]), nst)
    xs  = expand(bytearray(d[xo:yo]),   nst)
    ys  = expand(bytearray(d[yo:]),     nst)
    recs = []
    for i in range(nst):
        c = cmd[i]
        if c == 0x90:          # END
            break
        recs.append((c, signed8(xs[i]), signed8(ys[i])))
    return dict(nst=nst, ext=(posX, posY, negX, negY), recs=recs)

# VIP command bytes (same as HUS): 0x80 stitch, 0x81 jump, 0x84 color change,
# 0x88 trim, 0x90 end.

# ---------------------------------------------------------------------------
# ZHS record encoding  (inverse of pyembroidery ZhsReader)
# ---------------------------------------------------------------------------
def enc_delta(dx, dy):
    """Pack a signed (dx,dy) stored delta into the interleaved (b1,b2) bytes."""
    def adj(v):                       # inverse of reader's >=63/<=-63 adjustment
        if v >= 64:  return v - 1
        if v <= -64: return v + 1
        return v
    x = adj(dx) & 0xFF
    y = adj(dy) & 0xFF
    b1 = b2 = 0
    # x bits: 0->b1.0 1->b2.1 2->b1.2 3->b2.3 4->b1.4 5->b2.5 6->b1.6 7->b2.7
    if x & 0x01: b1 |= 0x01
    if x & 0x02: b2 |= 0x02
    if x & 0x04: b1 |= 0x04
    if x & 0x08: b2 |= 0x08
    if x & 0x10: b1 |= 0x10
    if x & 0x20: b2 |= 0x20
    if x & 0x40: b1 |= 0x40
    if x & 0x80: b2 |= 0x80
    # y bits: 0->b2.0 1->b1.1 2->b2.2 3->b1.3 4->b2.4 5->b1.5 6->b2.6 7->b1.7
    if y & 0x01: b2 |= 0x01
    if y & 0x02: b1 |= 0x02
    if y & 0x04: b2 |= 0x04
    if y & 0x08: b1 |= 0x08
    if y & 0x10: b2 |= 0x10
    if y & 0x20: b1 |= 0x20
    if y & 0x40: b2 |= 0x40
    if y & 0x80: b1 |= 0x80
    return b1, b2

BLOCK = 84   # a checksum record is emitted after every 84 data records

def block_checksum(block_bytes):
    s = sum(block_bytes) & 0xFFFF          # 16-bit sum of every byte in the block
    return bytes([0x10, s & 0xFF, (s >> 8) & 0xFF])   # little-endian

def build_stream(recs):
    """recs = VIP data records (single-color, pen-down). Returns
    (stream_bytes, ndata, nmoves, (lastX,lastY), data_records)."""
    data = []
    c0, dx0, dy0 = recs[0]
    data.append((0x01, dx0, dy0))     # first record -> MOVE (jump-in)
    data.append((0x02, 0, 0))         # tie-in duplicate stitch
    for c, dx, dy in recs[1:]:
        data.append((0x02, dx, dy))   # everything else -> STITCH
    ndata  = len(data)
    nmoves = sum(1 for r in data if r[0] == 0x01)
    lastX  = sum(r[1] for r in data)
    lastY  = sum(r[2] for r in data)

    out = bytearray()
    cur = bytearray()
    cnt = 0
    for ctrl, dx, dy in data:
        b1, b2 = enc_delta(dx, dy)
        cur += bytes([ctrl, b1, b2]); cnt += 1
        if cnt == BLOCK:
            out += cur; out += block_checksum(cur); cur = bytearray(); cnt = 0
    cur += bytes([0x80, 0, 0])         # END record
    out += cur; out += block_checksum(cur)
    return out, ndata, nmoves, (lastX, lastY), data

# ---------------------------------------------------------------------------
# ZHS writer
# ---------------------------------------------------------------------------
# Fixed 155-byte prefix (header 0..0x85 + single-color palette block 0x86..0x9a).
# Constant for single-color designs; numeric fields are patched below.
def _template():
    # colour block: count=1, RGB=0x348D1A, strlen=8, string="&$&#&#&%"
    t = bytearray(0x9B)
    t[0:7] = b"HSING12"
    struct.pack_into("<I", t, 0x0F, 0x9B)   # stitchStart
    struct.pack_into("<I", t, 0x13, 0x86)   # headerStart
    struct.pack_into("<I", t, 0x17, 0x96)   # constant 150
    struct.pack_into("<I", t, 0x70, 2)      # constant
    struct.pack_into("<I", t, 0x74, 0x8C)   # constant 140
    t[0x28:0x2C] = b"0000"
    struct.pack_into("<H", t, 0x2C, 1000); struct.pack_into("<H", t, 0x2E, 1000)
    t[0x65] = 0x01
    # palette
    t[0x86] = 0x01
    t[0x87:0x8A] = bytes([0x34, 0x8D, 0x1A])   # RGB 24-bit big-endian
    struct.pack_into("<H", t, 0x8A, 8)
    t[0x8C:0x94] = b"&$&#&#&%"
    return t

def convert(vip_path, out_path, field_0x83=0):
    v = read_vip(vip_path)
    if any(c != 0x80 for c, _, _ in v["recs"]):
        raise NotImplementedError(
            "This file has jumps/trims/color-changes. ZHS output is only VERIFIED "
            "for single-color pure-stitch designs. Get sample .zhs pairs first.")
    stream, ndata, nmoves, (lx, ly), data = build_stream(v["recs"])
    posX, posY, negX, negY = v["ext"]
    nst = ndata - nmoves
    h = _template()
    struct.pack_into("<I", h, 0x07, ndata + 1)
    struct.pack_into("<I", h, 0x0B, nst)
    struct.pack_into("<h", h, 0x1C, posX); struct.pack_into("<h", h, 0x1E, negX)
    struct.pack_into("<h", h, 0x22, posY); struct.pack_into("<h", h, 0x24, negY)
    struct.pack_into("<I", h, 0x68, nst)
    struct.pack_into("<h", h, 0x6C, data[0][1]); struct.pack_into("<h", h, 0x6E, data[0][2])
    struct.pack_into("<h", h, 0x7B, lx); struct.pack_into("<h", h, 0x7D, ly)
    struct.pack_into("<H", h, 0x7F, (len(stream) // 3) - 2)
    struct.pack_into("<H", h, 0x83, field_0x83 & 0xFFFF)   # editor metadata; see docs
    open(out_path, "wb").write(bytes(h) + bytes(stream))
    return out_path

# ---------------------------------------------------------------------------
# Verification helper (functional round-trip)
# ---------------------------------------------------------------------------
def verify(vip_path, ref_zhs_path=None):
    from pyembroidery import EmbPattern, ZhsReader
    tmp = "/tmp/_verify.zhs"
    convert(vip_path, tmp)
    # 1) functional: absolute stitch path must match the VIP source
    v = read_vip(vip_path)
    vx = vy = 0; vpath = []
    for c, dx, dy in v["recs"]:
        vx += dx; vy += dy; vpath.append((vx, -vy))
    p = EmbPattern(); ZhsReader.read(open(tmp, "rb"), p)
    zpath = [(s[0], s[1]) for s in p.stitches if s[2] in (0, 1)]
    def strip(a):
        o = []
        for e in a:
            if not o or o[-1] != e: o.append(e)
        return o
    print("functional path match:", strip(vpath) == strip(zpath))
    # 2) if a reference .zhs is given, byte-diff
    if ref_zhs_path:
        gen = open(tmp, "rb").read(); ref = open(ref_zhs_path, "rb").read()
        diffs = [i for i in range(min(len(gen), len(ref))) if gen[i] != ref[i]]
        print(f"byte-identical: {gen == ref} | diffs at {[hex(i) for i in diffs]} | len {len(gen)} vs {len(ref)}")

if __name__ == "__main__":
    if len(sys.argv) >= 4 and sys.argv[1] == "convert":
        print("wrote", convert(sys.argv[2], sys.argv[3]))
    elif len(sys.argv) >= 3 and sys.argv[1] == "verify":
        verify(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else None)
    else:
        print(__doc__)
